---
theme: jekyll-theme-slate
title: The Tuatarian Website
description: Everything I make!
---

# That time that 80,000 people tried to levitiate the Pentagon

This was part of a 1 week video challenge that I did with my friend, BattleAnimation. The challenge entailed:
   - 1 week to make and publish the entire video, starting on Sunday, June 28 and ending on Sunday, July 5
   - The main video must be under 1 minute in length, and must be recorded in 1 take (Endcard can be another take, as long as it contains no information)
   
This video was absurdly fast, even in comparison to my other videos which I intentionally make to be much faster than most. I can't emphasize enough, **please watch the video at a lower speed if this was too fast for you**. That being said, here's some more links and information
   
Further reading! Here are the Wikipedia pages for [Abbie Hoffman](https://en.wikipedia.org/wiki/Abbie_Hoffman), [Jerry Rubin](https://en.wikipedia.org/wiki/Jerry_Rubin), [Pigasus](https://en.wikipedia.org/wiki/Pigasus_(politics)) (who is actually pretty interesting but got shunted to about a second of joke within the video), and the [National Mobilization Committee to End the War in Vietnam](https://en.wikipedia.org/wiki/National_Mobilization_Committee_to_End_the_War_in_Vietnam) who were mostly behind the March on the Pentagon. 
   
Abbie Hoffman was actually a really interesting guy, I fully reccommend reading more on him. I understand this page is a bit half baked, but in my defence it is the last day and I'm not yet done with audio or the thumbnail. Thanks for reading!
